export const SET_TOKEN = 'SET_TOKEN'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_PROJECTSURVEY_INFO = 'SET_PROJECTSURVEY_INFO'

export const SET_TASKSURVEY_INFO = 'SET_TASKSURVEY_INFO'

export const SET_SURVEYINFOTYPE = 'SET_SURVEYINFOTYPE'

export const SET_MYPROJECT_INFO = 'SET_MYPROJECT_INFO'

export const SET_COMPLETEDPROJECT_INFO = 'SET_COMPLETEDPROJECT_INFO'
